INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MESSAGEUTILS messageutils)

FIND_PATH(
    MESSAGEUTILS_INCLUDE_DIRS
    NAMES messageutils/api.h
    HINTS $ENV{MESSAGEUTILS_DIR}/include
        ${PC_MESSAGEUTILS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREEFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MESSAGEUTILS_LIBRARIES
    NAMES gnuradio-messageutils
    HINTS $ENV{MESSAGEUTILS_DIR}/lib
        ${PC_MESSAGEUTILS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MESSAGEUTILS DEFAULT_MSG MESSAGEUTILS_LIBRARIES MESSAGEUTILS_INCLUDE_DIRS)
MARK_AS_ADVANCED(MESSAGEUTILS_LIBRARIES MESSAGEUTILS_INCLUDE_DIRS)

